set(headers ${headers}
	include/PCH.h
	src/Data/CreatedObjectManager.h
	src/Data/EnchantArtManager.h
	src/Events/ActivationListener.h
	src/Ext/AmmoEnchantmentController.h
	src/Ext/ArrowEffectController.h
	src/Ext/EnchantConstructMenu.h
	src/Ext/NiAVObject.h
	src/Ext/TESAmmo.h
	src/Hooks/Disenchant.h
	src/Hooks/Enchanting.h
	src/Hooks/FilterFlags.h
	src/Hooks/Gameplay.h
	src/Hooks/Misc.h
	src/Hooks/SkyUI.h
	src/Hooks/VFX.h
	src/Papyrus/AmmoEnchanting.h
	src/RE/BSResource.h
	src/RE/Offset.h
	src/Serialization/Serialization.h
	src/Settings/GlobalSettings.h
	src/Settings/INISettings.h
	src/Translation/Translation.h
)
